# Generated by Django 2.2.2 on 2020-11-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('device_no', models.CharField(max_length=50)),
                ('time', models.DateTimeField(unique=True)),
                ('current', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('voltage', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
            ],
        ),
    ]
